---
- hosts: nextcloud
  become: yes
  tasks:

  - name: Create tailscale dir on server
    ansible.builtin.file:
        path: /var/lib/tailscale
        state: directory

  - name: Copy docker compose config to server
    ansible.builtin.copy:
        src: ./config/docker-compose.yaml
        dest: /home/root/

  - name: Copy tailscale watchdog to server
    ansible.builtin.copy:
        src: ./config/tailscale-watchdog.sh
        dest: /home/root/
        mode: a+x

  - name: Copy .env config to server
    ansible.builtin.copy:
        src: ./config/.env
        dest: /home/root/

  - name: Create data directory
    ansible.builtin.file:
      path: /mnt/ncdata
      state: directory
      # owner: your_user
      # group: your_group
      mode: '750'

  - name: Run docker-compose up
    shell: cd /home/root/ && docker compose up -d
